Manu\TfeBundle\Entity\Categorie:
    type: entity
    table: categorie
    id:
      id:
        type: integer
        generator: { strategy: AUTO}
    fields:
      nom:
        type: string
        length: 255
        unique: true
      custom:
        type: boolean
        options:
          default: false
    oneToMany:
      questions:
        targetEntity: Question
        mappedBy: categorie
