parameters:
#    manu_tfe.example.class: Manu\TfeBundle\Example

services:
#    manu_tfe.example:
#        class: %manu_tfe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    manu.tfe.admin.role:
        class: Manu\TfeBundle\Admin\RoleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tfe, label: Roles }
        arguments: [null, Manu\TfeBundle\Entity\Role, ManuTfeBundle:RoleAdmin]
    manu.tfe.admin.user:
        class: Manu\TfeBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tfe, label: Utilisateurs }
        arguments: [null, Manu\TfeBundle\Entity\User, ManuTfeBundle:UserAdmin]
    manu.tfe.admin.niveau:
        class: Manu\TfeBundle\Admin\NiveauAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tfe, label: Niveaux }
        arguments: [null, Manu\TfeBundle\Entity\Niveau, ManuTfeBundle:NiveauAdmin]
    manu.tfe.admin.categorie:
        class: Manu\TfeBundle\Admin\CategorieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tfe, label: Categories }
        arguments: [null, Manu\TfeBundle\Entity\Categorie, ManuTfeBundle:CategorieAdmin]
    manu.tfe.admin.question:
        class: Manu\TfeBundle\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tfe, label: Questions }
        arguments: [null, Manu\TfeBundle\Entity\Question, ManuTfeBundle:QuestionAdmin]
    manu.tfe.admin.statistique:
        class: Manu\TfeBundle\Admin\StatistiqueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tfe, label: Statistiques }
        arguments: [null, Manu\TfeBundle\Entity\Statistique, ManuTfeBundle:StatistiqueAdmin]
