<?php

namespace Manu\TfeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('id'=>'asc'));
    }
}
