<?php

namespace Manu\TfeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends EntityRepository
{
    /**
     * find Statistiques
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getStatistiquesOfTheDayByUser($userid)
    {
        $today = (new \DateTime())->setTime(0,0);
        $query = $this->createQueryBuilder('a');
        $query->where('a.user = :user')
            ->andWhere('a.date >= :today')
            ->setParameters(array(
                'user' => $userid,
                'today' => $today));
        return $query->getQuery()->getResult();
    }
}
